import { useMemo, useState } from 'react';
import { Bell, ChevronDown, ChevronLeft, ChevronRight, Droplets, Home, Leaf, MapPin, Plus, Search, Settings, Sprout, Sun, X } from 'lucide-react';
import { activity, gardens, plants, type Plant, type Stage } from './data';

type View = 'home'|'plants'|'gardens'|'settings';
const stages: Stage[] = ['Seed','Germinating','Seedling','Vegetative','Flowering/Fruiting','Harvest'];

function Header({garden,setGarden}:{garden:string;setGarden:(g:string)=>void}) {
  return <header><div className="brand"><span className="brand-mark">R<span>🌱</span>OT</span><small>ME</small></div><button className="garden-switch" onClick={()=>setGarden(garden==='All gardens'?'Home':'All gardens')}><MapPin size={15}/>{garden}<ChevronDown size={15}/></button><button className="icon-btn" aria-label="Notifications"><Bell size={20}/><i/></button></header>;
}

function HomeView({openPlant, garden}:{openPlant:(p:Plant)=>void;garden:string}) {
  const visible = garden==='All gardens' ? plants : plants.filter(p=>p.garden===garden);
  return <main>
    <section className="hello"><p>Tuesday, 23 September</p><h1>Morning, dirt lover.</h1><span>Your plants have been gossiping.</span></section>
    <section className="weather"><div className="weather-icon">☀️</div><div><b>18°</b><span>Perfect pottering weather</span></div><div className="weather-side"><b>23° / 12°</b><span>London · Sunny</span></div></section>
    <section><div className="section-title"><div><label>TODAY</label><h2>Needs your love</h2></div><button>See all <ChevronRight size={16}/></button></div>
      <div className="task-scroll">
        {visible.filter(p=>p.water==='Today' || p.moisture==='Wet').map(p=><button className="task-card" key={p.id} onClick={()=>openPlant(p)}><img src={p.photo}/><div><span className={`pill ${p.moisture.toLowerCase()}`}>{p.moisture==='Wet'?'💦 Too moist':'💧 Thirsty'}</span><h3>{p.name}</h3><p>{p.garden} · {p.location}</p><strong>{p.moisture==='Wet'?"Fuck, that’s moist":"Give me a drink"}</strong></div></button>)}
      </div>
    </section>
    <section className="quick"><div className="section-title"><div><label>QUICK PEEK</label><h2>Your growing empire</h2></div></div><div className="stat-grid"><div><Sprout/><b>{visible.length}</b><span>plants growing</span></div><div><Droplets/><b>{visible.filter(p=>p.water==='Today').length}</b><span>need watering</span></div><div><span className="seed-icon">◉</span><b>{visible.filter(p=>p.stage==='Seedling').length}</b><span>tiny seedlings</span></div></div></section>
    <section><div className="section-title"><div><label>THE NURSERY</label><h2>Fresh little things</h2></div><button onClick={()=>null}>View plants <ChevronRight size={16}/></button></div><div className="seedling-row">{visible.filter(p=>['Seedling','Vegetative'].includes(p.stage)).slice(0,3).map(p=><button onClick={()=>openPlant(p)} key={p.id}><img src={p.photo}/><b>{p.name}</b><span>{p.stage}</span></button>)}</div></section>
    <section><div className="section-title"><div><label>RECENTLY IN THE DIRT</label><h2>Garden gossip</h2></div></div><div className="activity">{activity.map(a=><div key={a.text}><i>{a.icon}</i><p><b>{a.text}</b><span>{a.meta}</span></p></div>)}</div></section>
  </main>;
}

function PlantsView({openPlant,onAdd}:{openPlant:(p:Plant)=>void;onAdd:()=>void}) {
 const [query,setQuery]=useState(''); const filtered=plants.filter(p=>(p.name+p.variety).toLowerCase().includes(query.toLowerCase()));
 return <main><div className="page-head"><label>THE GREEN GANG</label><h1>Your plants</h1><p>All your leafy dependants, in one place.</p></div><div className="search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a plant..."/></div><div className="plant-grid">{filtered.map(p=><button className="plant-card" onClick={()=>openPlant(p)} key={p.id}><img src={p.photo}/><span className={`moisture-dot ${p.moisture.toLowerCase()}`}/><div><small>{p.stage}</small><h3>{p.name}</h3><p>{p.variety}</p><span><MapPin size={12}/>{p.garden} · {p.location}</span></div></button>)}</div><button className="fab" onClick={onAdd}><Plus/> Add plant</button></main>
}

function GardensView(){return <main><div className="page-head"><label>YOUR PATCHES</label><h1>Gardens</h1><p>Because one patch of dirt is never enough.</p></div>{gardens.map((g,i)=><article className="garden-card" key={g.name}><div className={`garden-art art-${i}`}>{g.emoji}</div><div><span>{g.count} PLANTS</span><h2>{g.name}</h2><p>{g.locations.join(' · ')}</p><button>Dig around <ChevronRight size={15}/></button></div></article>)}<button className="outline-add"><Plus/> Add another patch</button></main>}

function PlantDetail({plant,back}:{plant:Plant;back:()=>void}){const [watered,setWatered]=useState(false);return <div className="detail"><div className="detail-hero" style={{backgroundImage:`linear-gradient(180deg,rgba(0,0,0,.08),rgba(11,42,28,.65)),url(${plant.photo})`}}><button onClick={back}><ChevronLeft/></button><button>•••</button><div><span>{plant.stage}</span><h1>{plant.name}</h1><p>{plant.variety}</p></div></div><main><div className="location-line"><MapPin size={17}/><b>{plant.garden}</b><span>·</span>{plant.location}</div><div className="detail-stats"><div><Droplets/><small>MOISTURE</small><b>{watered?'Perfect':plant.moisture}</b></div><div><Sun/><small>SUN</small><b>{plant.sun.split(' · ')[0]}</b></div><div><Sprout/><small>PLANTED</small><b>{plant.planted.split(' ')[0]} {plant.planted.split(' ')[1]}</b></div></div><button className="water-button" onClick={()=>setWatered(true)}><Droplets/>{watered?'Watered. Nice and wet.':'Water me now'}</button><section className="info-card"><label>NEXT UP</label><h2>{plant.repot}</h2><p>{plant.note}</p></section><section className="info-card"><label>LIFE STAGE</label><div className="stage-track">{stages.map((s,i)=><i key={s} className={stages.indexOf(plant.stage)>=i?'active':''}/>)}</div><b>{plant.stage}</b><p>Look at you, growing and shit.</p></section><section className="info-card"><label>NOTES FROM THE UNDERGROWTH</label><p>{plant.note}</p></section></main></div>}

function AddPlant({close}:{close:()=>void}){const [done,setDone]=useState(false);return <div className="sheet-backdrop"><div className="sheet"><button className="sheet-close" onClick={close}><X/></button>{done?<div className="success">🌱<h2>Rooted and ready!</h2><p>Your new leafy child joined the gang.</p><button onClick={close}>Lovely stuff</button></div>:<><label>NEW SPROUT</label><h1>Plant something</h1><p>Tell us about your latest dirt-dweller.</p><form onSubmit={e=>{e.preventDefault();setDone(true)}}><label>PLANT NAME<input required placeholder="e.g. Kale Me Maybe"/></label><label>VARIETY<input placeholder="e.g. Tuscan kale"/></label><div className="form-row"><label>GARDEN<select><option>Home</option><option>Mum’s House</option></select></label><label>LOCATION<select><option>Back yard</option><option>Patio</option><option>Sunny side</option></select></label></div><label>LIFE STAGE<select>{stages.map(s=><option key={s}>{s}</option>)}</select></label><button className="submit">Get it in the dirt</button></form></>}</div></div>}

export default function App(){const [view,setView]=useState<View>('home');const [garden,setGarden]=useState('All gardens');const [selected,setSelected]=useState<Plant|null>(null);const [adding,setAdding]=useState(false);const content=useMemo(()=>view,[view]);if(selected)return <PlantDetail plant={selected} back={()=>setSelected(null)}/>;return <div className="app"><Header garden={garden} setGarden={setGarden}/>{content==='home'?<HomeView openPlant={setSelected} garden={garden}/>:content==='plants'?<PlantsView openPlant={setSelected} onAdd={()=>setAdding(true)}/>:content==='gardens'?<GardensView/>:<main><div className="page-head"><label>KEEP IT PERSONAL</label><h1>Settings</h1><p>Notifications, units and other bits and bobs.</p></div><div className="info-card"><h2>ROOT ME</h2><p>Get dirty. Grow stuff.</p><p>Version 0.1.0 · Made with muddy hands.</p></div></main>}<nav>{([['home',Home,'Home'],['plants',Leaf,'Plants'],['gardens',MapPin,'Gardens'],['settings',Settings,'Settings']] as const).map(([id,Icon,label])=><button className={view===id?'active':''} onClick={()=>setView(id)} key={id}><Icon/><span>{label}</span></button>)}</nav>{view==='home'&&<button className="floating-plus" onClick={()=>setAdding(true)}><Plus/></button>}{adding&&<AddPlant close={()=>setAdding(false)}/>}</div>}
