import { useState } from 'react';
import { Bell, ChevronDown, ChevronLeft, ChevronRight, Droplets, Home, Leaf, MapPin, Plus, Search, Settings, Sprout, Sun, X } from 'lucide-react';
import { activity, gardens, plants, type Garden, type Plant, type Stage } from './data';

type View = 'home'|'plants'|'gardens'|'settings';
const stages: Stage[] = ['Seed','Germinating','Seedling','Vegetative','Flowering/Fruiting','Harvest'];

function Brand() {
  return <div className="brand" aria-label="ROOT ME — Get dirty. Grow stuff.">
    <span className="brand-art" aria-hidden="true"><span>♣</span><i /></span>
    <span className="brand-type"><b>ROOT ME</b><small>GET DIRTY. GROW STUFF.</small></span>
  </div>;
}

function Header({garden,setGarden}:{garden:string;setGarden:(g:string)=>void}) {
  return <header><Brand/><label className="garden-switch"><MapPin size={14}/><span className="sr-only">Current garden</span><select aria-label="Current garden" value={garden} onChange={e=>setGarden(e.target.value)}>{gardens.map(g=><option key={g.name}>{g.name}</option>)}</select><ChevronDown size={14}/></label><button className="icon-btn" aria-label="Notifications"><Bell size={19}/><i/></button></header>;
}

function WeatherState({garden}:{garden:Garden}) {
  return <section className="weather" aria-label={`Weather for ${garden.name}`}><div className="weather-icon"><MapPin/></div><div><span>WEATHER AT {garden.name.toUpperCase()}</span><b>Connect your patch</b><p>{garden.location}. Add it to see local growing conditions.</p></div><button aria-label={`Configure location for ${garden.name}`}>Set location</button></section>;
}

function HomeView({openPlant, gardenName}:{openPlant:(p:Plant)=>void;gardenName:string}) {
  const garden = gardens.find(g=>g.name===gardenName) ?? gardens[0];
  const visible = plants.filter(p=>p.garden===garden.name);
  const attention = visible.filter(p=>p.water==='Today' || p.moisture==='Wet');
  const seedlings = visible.filter(p=>['Seedling','Vegetative'].includes(p.stage));
  const recent = activity.filter(a=>a.garden===garden.name);
  return <main>
    <section className="hello"><p>{garden.name.toUpperCase()} · TODAY</p><h1>Morning, dirt lover.</h1><span>{attention.length ? `Your plants have been gossiping. ${attention.length} need a word.` : 'All quiet in the undergrowth. Suspiciously quiet.'}</span></section>
    <WeatherState garden={garden}/>
    <section><div className="section-title"><div><label>NEEDS ATTENTION</label><h2>Needs your love</h2></div><span className="section-count">{attention.length} waiting</span></div>
      {attention.length ? <div className="task-scroll" aria-label="Plants needing attention">{attention.map(p=><button className="task-card" key={p.id} onClick={()=>openPlant(p)}><img src={p.photo} alt=""/><div><span className={`pill ${p.moisture.toLowerCase()}`}>{p.moisture==='Wet'?'💦 Soggy bits':'💧 Thirsty'}</span><h3>{p.name}</h3><p>{p.location}</p><strong>{p.moisture==='Wet'?"Fuck, that’s moist.":'Give me a drink.'}</strong></div></button>)}</div> : <div className="empty-card">🌿 <div><b>No drama in this patch.</b><span>Everyone’s hydrated and behaving themselves.</span></div></div>}
    </section>
    <section className="watering"><div className="section-title"><div><label>WATERING</label><h2>Thirst traps</h2></div></div><div className="watering-card"><Droplets/><div><b>{visible.filter(p=>p.water==='Today').length ? `${visible.filter(p=>p.water==='Today').length} want a good soaking` : 'No one needs a soaking'}</b><span>{visible.filter(p=>p.water==='Today').length ? 'Today’s thirsty little lineup is ready.' : 'Put the hose down. You’ve done enough.'}</span></div><ChevronRight/></div></section>
    <section className="quick"><div className="section-title"><div><label>QUICK PEEK</label><h2>{garden.name} at a glance</h2></div></div><div className="stat-grid"><div><Sprout/><b>{visible.length}</b><span>bushy babes</span></div><div><Droplets/><b>{visible.filter(p=>p.water==='Today').length}</b><span>thirsty plants</span></div><div><span className="seed-icon">◉</span><b>{seedlings.length}</b><span>young things</span></div><div><MapPin/><b>{garden.locations.length}</b><span>growing spots</span></div></div></section>
    <section><div className="section-title"><div><label>THE NURSERY</label><h2>Fresh little things</h2></div><button>My Bushes <ChevronRight size={16}/></button></div>{seedlings.length ? <div className="seedling-row">{seedlings.slice(0,3).map(p=><button onClick={()=>openPlant(p)} key={p.id}><img src={p.photo} alt=""/><b>{p.name}</b><span>{p.stage}</span></button>)}</div> : <div className="empty-card">🌱 <div><b>No tiny shoots yet.</b><span>Plant some seeds and start something filthy.</span></div></div>}</section>
    <section><div className="section-title"><div><label>RECENTLY IN THE DIRT</label><h2>Garden gossip</h2></div></div><div className="activity">{recent.length ? recent.map(a=><div key={a.text}><i>{a.icon}</i><p><b>{a.text}</b><span>{a.meta}</span></p></div>) : <div><i>🤫</i><p><b>Nothing to spill yet</b><span>Your dirty deeds will appear here.</span></p></div>}</div></section>
  </main>;
}

function PlantsView({openPlant,onAdd}:{openPlant:(p:Plant)=>void;onAdd:()=>void}) { const [query,setQuery]=useState(''); const filtered=plants.filter(p=>(p.name+p.variety).toLowerCase().includes(query.toLowerCase())); return <main><div className="page-head"><label>THE GREEN GANG</label><h1>My Bushes</h1><p>Every leafy dependant and unruly bit of growth.</p></div><div className="search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a plant..."/></div><div className="plant-grid">{filtered.map(p=><button className="plant-card" onClick={()=>openPlant(p)} key={p.id}><img src={p.photo} alt=""/><span className={`moisture-dot ${p.moisture.toLowerCase()}`}/><div><small>{p.stage}</small><h3>{p.name}</h3><p>{p.variety}</p><span><MapPin size={12}/>{p.garden} · {p.location}</span></div></button>)}</div><button className="fab" onClick={onAdd}><Plus/> Add plant</button></main> }

function GardensView({selectGarden}:{selectGarden:(garden:string)=>void}){return <main><div className="page-head"><label>YOUR PATCHES</label><h1>Gardens</h1><p>Choose where you want to get dirty.</p></div>{gardens.map((g,i)=><article className="garden-card" key={g.name}><div className={`garden-art art-${i}`}>{g.emoji}</div><div><span>{g.count} PLANTS · {g.locations.length} SPOTS</span><h2>{g.name}</h2><p>{g.locations.join(' · ')}</p><button onClick={()=>selectGarden(g.name)}>Open this patch <ChevronRight size={15}/></button></div></article>)}<button className="outline-add"><Plus/> Add another patch</button></main>}

function PlantDetail({plant,back}:{plant:Plant;back:()=>void}){const [watered,setWatered]=useState(false);return <div className="detail"><div className="detail-hero" style={{backgroundImage:`linear-gradient(180deg,rgba(0,0,0,.08),rgba(11,42,28,.65)),url(${plant.photo})`}}><button onClick={back} aria-label="Back"><ChevronLeft/></button><button aria-label="Plant options">•••</button><div><span>{plant.stage}</span><h1>{plant.name}</h1><p>{plant.variety}</p></div></div><main><div className="location-line"><MapPin size={17}/><b>{plant.garden}</b><span>·</span>{plant.location}</div><div className="detail-stats"><div><Droplets/><small>MOISTURE</small><b>{watered?'Perfect':plant.moisture}</b></div><div><Sun/><small>SUN</small><b>{plant.sun.split(' · ')[0]}</b></div><div><Sprout/><small>PLANTED</small><b>{plant.planted.split(' ')[0]} {plant.planted.split(' ')[1]}</b></div></div><button className="water-button" onClick={()=>setWatered(true)}><Droplets/>{watered?'Watered. Nice and wet.':'Water me now'}</button><section className="info-card"><label>NEXT UP</label><h2>{plant.repot}</h2><p>{plant.note}</p></section><section className="info-card"><label>LIFE STAGE</label><div className="stage-track">{stages.map((s,i)=><i key={s} className={stages.indexOf(plant.stage)>=i?'active':''}/>)}</div><b>{plant.stage}</b><p>Look at you, growing and shit.</p></section></main></div>}

function AddPlant({close}:{close:()=>void}){const [done,setDone]=useState(false);return <div className="sheet-backdrop"><div className="sheet"><button className="sheet-close" onClick={close} aria-label="Close"><X/></button>{done?<div className="success">🌱<h2>Rooted and ready!</h2><p>Your new leafy child joined the gang.</p><button onClick={close}>Lovely stuff</button></div>:<><label>NEW SPROUT</label><h1>Plant something</h1><p>Tell us about your latest dirt-dweller.</p><form onSubmit={e=>{e.preventDefault();setDone(true)}}><label>PLANT NAME<input required placeholder="e.g. Kale Me Maybe"/></label><label>VARIETY<input placeholder="e.g. Tuscan kale"/></label><div className="form-row"><label>GARDEN<select>{gardens.map(g=><option key={g.name}>{g.name}</option>)}</select></label><label>LOCATION<select><option>Back yard</option><option>Patio</option><option>Sunny side</option></select></label></div><label>LIFE STAGE<select>{stages.map(s=><option key={s}>{s}</option>)}</select></label><button className="submit">Get it in the dirt</button></form></>}</div></div>}

export default function App(){const [view,setView]=useState<View>('home');const [garden,setGarden]=useState('Home');const [selected,setSelected]=useState<Plant|null>(null);const [adding,setAdding]=useState(false);if(selected)return <PlantDetail plant={selected} back={()=>setSelected(null)}/>;const chooseGarden=(name:string)=>{setGarden(name);setView('home')};return <div className="app"><Header garden={garden} setGarden={setGarden}/>{view==='home'?<HomeView openPlant={setSelected} gardenName={garden}/>:view==='plants'?<PlantsView openPlant={setSelected} onAdd={()=>setAdding(true)}/>:view==='gardens'?<GardensView selectGarden={chooseGarden}/>:<main><div className="page-head"><label>KEEP IT PERSONAL</label><h1>Settings</h1><p>Locations, notifications and other bits and bobs.</p></div>{gardens.map(g=><section className="info-card" key={g.name}><label>WEATHER LOCATION</label><h2>{g.name}</h2><p>{g.location}. Weather stays hidden until you connect one—no made-up forecasts here.</p><button className="text-button">Set location</button></section>)}</main>}<nav>{([['home',Home,'Home'],['plants',Leaf,'My Bushes'],['gardens',MapPin,'Gardens'],['settings',Settings,'Settings']] as const).map(([id,Icon,label])=><button className={view===id?'active':''} onClick={()=>setView(id)} key={id}><Icon/><span>{label}</span></button>)}</nav>{view==='home'&&<button className="floating-plus" onClick={()=>setAdding(true)} aria-label="Add plant"><Plus/></button>}{adding&&<AddPlant close={()=>setAdding(false)}/>}</div>}
